### ISSUE TITLE
key error: 'encoder' when generating pseudo labels in UFLD-SGADA

### ISSUE THREAD

**Issue by kshitij11** [juliangebele/CARLANE#1]
Hi,

I am trying to generate pseudo labels in UFLD-SGADA but I get the following error:
python generate_pseudo_labels.py configs/molane.py
Traceback (most recent call last):
  File "generate_pseudo_labels.py", line 364, in <module>
    encoder_state_dict = {key: value for key, value in adda_state_dict["encoder"].items() if "model" in key or "aux" in key or "pool" in key}
KeyError: 'encoder'

The pretrained model I am using is UFLD-SO downloaded from here for molane (ufld_so_resnet18_ep149.pth): https://carlanebenchmark.github.io/

Thanks!

**Comment by juliangebele** [comment]
Hey,

you need to choose a different pretrained model for UFLD-SGADA. This method requires a pretrained UFLD-ADDA model. You should be good to go with [this](https://drive.google.com/file/d/1eZRTJs4N2weEVrVPVvO0iQTGtYd0Clor/view?usp=sharing) one. 

Kind regards!

**Comment by kshitij11** [comment]
Thanks, that worked.
